import { GameMapData } from '../map';
import { Status, TerritoryType, TerritoryProperty, TerritoryAction, propsToType, propsToActions } from '../values';

const testMap: GameMapData = {
  id: 'test-map',
  type: 'map',
  nextId: 1,
  playerIds: ['#PR', '#PB', '#PG'],
  territoryIds: ['#T1', '#T2', '#T3', '#T4', '#T5'],
  edgeIds: ['#E12', '#E13', '#E23', '#E34', '#E35', '#E45'],
  unitIds: ['#UR1', '#UR2', '#UB3', '#U1', '#0'],
  dataMap: {
    '#0': {
      destinationId: null,
      id: '#0',
      locationId: '#T2',
      playerId: '#PR',
      statuses: [],
      type: 'unit',
    },
    '#PR': {
      id: '#PR',
      type: 'player',
      colour: 16711680,
      gold: 5,
      goldProduction: 0,
      ready: false,
    },
    '#PB': {
      id: '#PB',
      type: 'player',
      colour: 255,
      gold: 4,
      goldProduction: 1,
      ready: false,
    },
    '#PG': {
      id: '#PG',
      type: 'player',
      colour: 10027263,
      gold: 13,
      goldProduction: 2,
      ready: false,
    },
    '#T1': {
      id: '#T1',
      type: 'territory',
      playerId: '#PR',
      edgeIds: ['#E12', '#E13'],
      food: 0,
      properties: [
        TerritoryProperty.SETTLED,
        TerritoryProperty.FARM,
        TerritoryProperty.FORT,
        TerritoryProperty.CITY,
        TerritoryProperty.CASTLE,
      ],
      currentAction: null,
    },
    '#T2': {
      id: '#T2',
      type: 'territory',
      playerId: '#PR',
      edgeIds: ['#E12', '#E23'],
      food: 3,
      properties: [],
      currentAction: null,
    },
    '#T3': {
      id: '#T3',
      type: 'territory',
      playerId: '#PB',
      edgeIds: ['#E13', '#E23', '#E34', '#E35'],
      food: 3,
      properties: [TerritoryProperty.SETTLED],
      currentAction: null,
    },
    '#T4': {
      id: '#T4',
      type: 'territory',
      playerId: null,
      edgeIds: ['#E34', '#E45'],
      food: 3,
      properties: [TerritoryProperty.SETTLED, TerritoryProperty.CITY],
      currentAction: null,
    },
    '#T5': {
      id: '#T5',
      type: 'territory',
      playerId: '#PG',
      edgeIds: ['#E35', '#E45'],
      food: 7,
      properties: [TerritoryProperty.SETTLED, TerritoryProperty.FARM],
      currentAction: null,
    },
    '#E12': {
      id: '#E12',
      type: 'edge',
      territoryAId: '#T1',
      territoryBId: '#T2',
    },
    '#E13': {
      id: '#E13',
      type: 'edge',
      territoryAId: '#T1',
      territoryBId: '#T3',
    },
    '#E23': {
      id: '#E23',
      type: 'edge',
      territoryAId: '#T2',
      territoryBId: '#T3',
    },
    '#E34': {
      id: '#E34',
      type: 'edge',
      territoryAId: '#T3',
      territoryBId: '#T4',
    },
    '#E35': {
      id: '#E35',
      type: 'edge',
      territoryAId: '#T3',
      territoryBId: '#T5',
    },
    '#E45': {
      id: '#E45',
      type: 'edge',
      territoryAId: '#T4',
      territoryBId: '#T5',
    },
    '#UR1': {
      id: '#UR1',
      type: 'unit',
      playerId: '#PR',
      locationId: '#T1',
      destinationId: null,
      statuses: [Status.DEFEND],
    },
    '#UR2': {
      id: '#UR2',
      type: 'unit',
      playerId: '#PR',
      locationId: '#T1',
      destinationId: null,
      statuses: [Status.DEFEND],
    },
    '#UB3': {
      id: '#UB3',
      type: 'unit',
      playerId: '#PB',
      locationId: '#T3',
      destinationId: null,
      statuses: [Status.DEFEND],
    },
    '#U1': {
      id: '#U1',
      type: 'unit',
      playerId: null,
      locationId: '#T4',
      destinationId: null,
      statuses: [Status.DEFEND],
    },
  },
};

export default testMap;
